name: Daily Coverage

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  go-coverage:
    name: Go Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go test -short -coverprofile=coverage.out ./...
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: agentx
          files: coverage.out
